"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&do#z232!-ozo4p4!6*pa4iou=%b=u(9i38_8o7mcz7_ud##%2'

# SECURITY WARNING: don't run with debug turned on in production!

# ✏️ ИЗМЕНЕНО: Теперь DEBUG динамически считывается из Docker (False для продакшена)
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    '130.49.128.168',  # IP вашего сервера
    'localhost',
    '127.0.0.1',
]

# ✏️ ИЗМЕНЕНО: Убрано условие if not DEBUG. Доверенный origin для CSRF должен быть всегда,
# чтобы админка не блокировала отправку форм (вход, сохранение товаров) через Nginx
CSRF_TRUSTED_ORIGINS = [
    "http://130.49.128.168",
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

        
    # Added libraries
    'rest_framework',
    'corsheaders',
    
    # Application
    'products',
]

MIDDLEWARE = [
    # это класс промежуточного слоя (middleware) для веб-фреймворка Django.
    # Он автоматически добавляет заголовки CORS (Cross-Origin Resource Sharing) к ответам сервера.
    # Это нужно, чтобы сайты на других доменах (например, фронтенд на React или Vue) могли отправлять запросы к вашему API на Django.
    # Должен быть в самом верху
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Разрешаем React (который обычно работает на порту 3000) делать запросы к API
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Настройки для хранения изображений товаров
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'online_shop_db',               # Имя базы, которую создали в pgAdmin
#         'USER': 'django_admin',                    # Стандартный пользователь PostgreSQL
#         'PASSWORD': 'Sdf567890Jhg',     # Пароль, который вы задали при установке
#         'HOST': '127.0.0.1',                   # Локальный адрес компьютера
#         'PORT': '5432',                        # Стандартный порт PostgreSQL
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'online_shop_db'),
        'USER': os.environ.get('DB_USER', 'django_admin'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'Sdf567890Jhg'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'), # Сработает локально, если нет Docker
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ✏️ ИЗМЕНЕНО: Итоговые и правильные настройки статики и медиа под Docker Volumes и Nginx
STATIC_URL = '/static/django/'
STATIC_ROOT = BASE_DIR / 'backend_static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'backend_media'
