version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - pg_catalog_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=online_shop_db
      - POSTGRES_USER=django_admin
      - POSTGRES_PASSWORD=Sdf567890Jhg
    ports:
      - "5432:5432"

  backend:
    build: ./backend_project
    volumes:
      - ./backend_project:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=online_shop_db
      - DB_USER=django_admin
      - DB_PASSWORD=Sdf567890Jhg
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    depends_on:
      - backend

volumes:
  pg_catalog_data:
  django_static:
  django_media: